version: '2.0'
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 8081:9411

  employee-service:
    container_name: employee-service
    image: mockserver/mockserver
    ports:
      - 8082:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
    - ./dist/employee-service:/config

  payroll-service:
    container_name: payroll-service
    image: mockserver/mockserver
    ports:
      - 8083:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - ./dist/payroll-service:/config
